# kind-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/am/code/airflow-dag-example/airflow-data/dags
        containerPath: /mnt/kind-data/airflow/dags
