apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual # Match the PV's storageClassName