apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/kind-data/airflow/dags # Path on the host machine
    type: Directory